eureka:
  client:
    enabled: false

database: mysql

spring:
  application:
    name: account

  cloud:
    config:
      uri: http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}
      fail-fast: true
      password: ${CONFIG_PASS:dev}
      username: user

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  resource:
    chain:
      compressed: true
      cache: true
    cache:
      period: 86400

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%t]){faint} %clr(%-40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO